os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
language: node_js
node_js:
  - '12'
cache:
  - apt: true
  - yarn: true
  - directories:
      - node_modules
      - $HOME/.electron
addons:
  apt:
    packages: zip
  homebrew:
    packages: zip
install:
  - yarn
script:
  - yarn dist
